apiVersion: v1
kind: Namespace
metadata:
  name: eventos-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: eventos-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: eventos-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: eventos-ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: eventos-cicd
