apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-svc.eventos-ops:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki-svc.eventos-ops:3100
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo-svc.eventos-ops:3200
    editable: false
